### ISSUE TITLE
Creating SMS template in message templates

### ISSUE THREAD

**Issue by dev-allinappli** [CiviCooP/org.civicoop.smsapi#11]
When creating a new SMS template, this has to be done when sending a SMS and being saved as a new template. 
It would also be practical to have the ability to create it like any other mailing template in domain.net/civicrm/admin/messageTemplates?reset=1. Looking in the database in the `civicrm_msg_template` table one can see that there is a column named 'is_sms'. When the SMS is saved while creating it, it is set to '1' in the database but when it is created from scratch as a message template, it stays on '0' like a normal e-mail and can't be used as a SMS template.

**Comment by kainuk** [comment]
Hi @allinappliadmin, I think it is a good idea. It can be better realized in a separate extension. The focus of this extension is to offer an API to make the SMS functionality available for other extensions.
