### ISSUE TITLE
Unable to give provider name by using SMS Api Extension

### ISSUE THREAD

**Issue by sandeepmohanty** [CiviCooP/org.civicoop.smsapi#2]
I downloaded SMS Api Extension (v1.3) in civicrm version 4.5.0.
After that i am unable to give Provider name.(As there is no option to give provider name)
Then i went to https://github.com/CiviCooP/org.civicoop.smsapi .... There in commits "fixed provider name fixed section". It showing two changing files which was missing in last released SMS Api version 1.3. 4.So i created CRM/Smsapi/CivirulesAction.mgd.php and CRM/Smsapi/CivirulesAction.php inside org.civicoop.smsapi (which is the extension diretory name)
When i opened --> Settings - SMS Provider --> Still creating of provider name option is not coming.

Please suggest.

Please provide a complete updated zip file of sms api. I saw which file you changed CivirulesAction.php that is missing sms api version 3 downloaded file.

**Comment by jaapjansma** [comment]
I am not really following you. What exactly is the problem? Did you setup an SMS provider in CiviCRM? 
Also keep in mind that I have developed this for one particiular client which was one CiviCRM version 4.4 and not 4.5.

**Comment by sandeepmohanty** [comment]
What is the use of using SMS API extension as it is not providing option for creating provider name. I knew the using of Mysmsmantra and Clickatell extension. But i want to use different Sms Provider for sending sms in civicrm. Can you suggest me atleast how to set up SMS provider if i am using SMS API extension. I tried in civicrm version 4.4.0 same issue.

**Comment by sandeepmohanty** [comment]
What is the use of using SMS API extension as it is not providing option
for creating provider name. I knew the using of Mysmsmantra and Clickatell
extension. But i want to use different Sms Provider for sending sms in
civicrm. Can you suggest me atleast how to set up SMS provider if i am
using SMS API extension. I tried in civicrm version 4.4.0 same issue.

**Comment by jaapjansma** [comment]
Without this extension you can only send sms messages form the user interface in CiviCRM. With this extension you have an api call for sending sms messages. 
This extension does not take care of the provider. You should Clikatell, or pswincom (in Norway). The provider extension depends on the SMS provider you have chosen.
