### ISSUE TITLE
Interaction with new send SMS permission

### ISSUE THREAD

**Issue by michaelmcandrew** [CiviCooP/org.civicoop.smsapi#5]
Hey there,

I am not sure if / how this API might be affected by the new Send SMS permission that is (hopefully!) coming to core but wanted to create an issue here to flag up that it is on its way, at least: https://github.com/civicrm/civicrm-core/pull/11590

**Comment by jaapjansma** [comment]
I dont know either. I do think this extension works without that permission and it could be that it is desired case. Imagine a use case where we use this api in civirules and a rule is setup that after a new donation comes in a thank you sms should be send. Than the user and the permission used are the one of the anonymous user.

**Comment by michaelmcandrew** [comment]
That makes two of us then :) Something to be aware of at least.

**Comment by kainuk** [comment]
Added it as a known issue to the README, here https://lab.civicrm.org/extensions/smsapi/-/blob/main/README.md .
