### ISSUE TITLE
Installer fails, "DB Error: no such table"

### ISSUE THREAD

**Issue by spronay** [CiviCooP/org.civicoop.smsapi#6]
Running the installer in Civi, I keep getting 

>Sorry, due to an error, we are unable to fulfill your request at the moment.
>You may want to contact your administrator or service provider with more
>details about what action you were performing when this occurred.
>
>DB Error: no such table

Running Civi 5.12.4 with WP 5.1.1

**Comment by kainuk** [comment]
Hi @spronay, I assume this caused because there is a hidden dependency on civirules. I am now moving the repository, I will make a new issue.

**Comment by kainuk** [comment]
Created a new issue for this at https://lab.civicrm.org/extensions/smsapi/-/issues/1
