### ISSUE TITLE
Deprecated function CRM_Core_OptionGroup::getValue

### ISSUE THREAD

**Issue by HikerBoricua** [CiviCooP/org.civicoop.smsapi#7]
Started getting the message below after installing emailapi and smsapi. Posting the heads up here because the emailapi repo is archived. Everything is working so not a roadblock ... yet?

Feb 25 12:04:20  [warning] Deprecated function CRM_Core_OptionGroup::getValue, use CRM_Core_PseudoConstant::getKey.
Array
(
    [civi.tag] => deprecated
)

Feb 25 12:04:20  [info] Inbound SMS recorded for cid=410.

**Comment by kainuk** [comment]
Hi @HikerBoricua, I cannot find the code in the smsapi. So, it must be the email API. That project moved to the CiviCRM GitLab. See https://lab.civicrm.org/extensions/emailapi. You can create an issue there (if it is still actual).
