### ISSUE TITLE
SMS won't send as no permission to send - but user has permission

### ISSUE THREAD

**Issue by clarkac1** [CiviCooP/org.civicoop.smsapi#8]
Using CiviRules to send an SMS, but it fails with the following message '[info] Civirules api action exception: You do not have the 'send SMS' permission. API call: Sms.send with params: provider_id="1", template_id="70", alternative_receiver_phone_number="", contact_id="545"'
However the user _does_ have permission to send an SMS.  Also tried a user who is an admin but that failed the same way.  Civi is at 5.19.4. SMS API at 1.5

**Comment by MegaphoneJon** [comment]
My pull request #13 gives a path forward here.
