### ISSUE TITLE
Send SMS from Contact page

### ISSUE THREAD

**Issue by dev-allinappli** [CiviCooP/org.civicoop.smsapi#9]
Like the e-mail capability, it would be great to send an individual SMS directly from the contact dashboard
![image](https://user-images.githubusercontent.com/62597730/98221522-06fcaf00-1f50-11eb-9236-566e8a026cf0.png)
Could this be possible?
Guillaume

**Comment by kainuk** [comment]
Hi @allinappliadmin, actually this is standard CiviCRM functionality. It, however only shows up when the contact has an active mobile number. 
![2023-06-29_20-14](https://github.com/CiviCooP/org.civicoop.smsapi/assets/14834891/37a7b62b-c465-4a0a-ac39-2ae8a08654af)
